import {Hero} from "./hero";

export const HEROES:Hero[]=[
  {id:1, avatar:"https://images.saymedia-content.com/.image/t_share/MTk2NzIzMTQ2NzMxMTAzMjUw/11-dogs-like-german-shepherd.png", name:"Axl", field:"German shepherd", info:"The German Shepherd[a] is a German breed of working dog of medium to large size. The breed was developed by Max von Stephanitz using various traditional German herding dogs from 1899." },
  {id:2, avatar:"https://cdn.britannica.com/82/232782-050-8062ACFA/Black-labrador-retriever-dog.jpg", name:"Angel", field:"Labrador", info:"The Labrador Retriever, or simply Labrador, is a British breed of retriever gun dog. It was developed in the United Kingdom from fishing dogs imported from the colony of Newfoundland (now a province of Canada), and was named after the Labrador region of that colony." },
  {id:3, avatar:"https://cdn.britannica.com/80/29280-050-A3A13277/Beagles-pets.jpg", name:"Advick", field:"Beagle", info:"Not only is the Beagle an excellent hunting dog and loyal companion, it is also happy-go-lucky, funny, and'¿thanks to its pleading expression'¿cute. They were bred to hunt in packs, so they enjoy company and are generally easygoing. There are two Beagle varieties: those standing under 13 inches at the shoulder, and those between 13 and 15 inches." },
  {id:4, avatar:"https://www.dailypaws.com/thmb/B6yWhzGpQZsg3kxMzLn-hvGIF7M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/siberian-husky-100800827-2000-9449ca147e0e4b819bce5189c2411188.jpg", name:"Zeus", field:"Husky", info:"Husky is a general term for a dog used in the polar regions, primarily and specifically for work as sled dogs. It refers to a traditional northern type, notable for its cold-weather tolerance and overall hardiness.[1][2] Modern racing huskies that maintain arctic breed traits (also known as Alaskan huskies) represent an ever-changing crossbreed of the fastest dogs." },
  {id:5, avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDj09nfNijtYJ9fp8h736GKQ9sMPnPiarC5ihfOVuoLfObMcf-rkDp7W1iysm3p3b5-8L5&s", name:"Shiro", field:"Shih Tzu", info:"The Shih Tzu is a sturdy dog with a small muzzle and normally has large dark brown eyes. The Chinese have described their head shapes as owl head and lion head, and their mouth as frog mouths. They have a soft and long double coat that will tangle and mat easily if not brushed at least every 2 or 3 days. " },


];
